#!/usr/bin/bash

set -e
set -o pipefail
set -u

if [ -z "${AZP_URL:-}" ]; then
  echo 1>&2 "error: missing AZP_URL environment variable"
  exit 1
fi

if [ -f /run/secrets/AZP_TOKEN ]; then
  AZP_TOKEN=${AZP_TOKEN:-$(cat /run/secrets/AZP_TOKEN)}
fi

if [ -z "${AZP_TOKEN:-}" ]; then
  echo 1>&2 "error: missing AZP_TOKEN environment variable"
  exit 1
fi

if [ -n "${AZP_WORK:-}" ]; then
  mkdir -p "$AZP_WORK"
fi

if [ -z "${TARGETARCH:-}" ]; then
  echo 1>&2 "error: missing TARGETARCH environment variable"
  exit 1
fi

AZP_AGENT_PACKAGES=$(curl -LsS \
    -u "user:${AZP_TOKEN}" \
    -H 'Accept:application/json;' \
    "${AZP_URL}/_apis/distributedtask/packages/agent?platform=${TARGETARCH}&top=1")

AZP_AGENT_PACKAGE_LATEST_URL=$(echo "${AZP_AGENT_PACKAGES}" | jq -r '.value[0].downloadUrl')

if [ -z "${AZP_AGENT_PACKAGE_LATEST_URL}" -o "${AZP_AGENT_PACKAGE_LATEST_URL}" == "null" ]; then
  echo 1>&2 "error: could not determine a matching Azure Pipelines agent"
  echo 1>&2 "check that account '$AZP_URL' is correct and the token is valid for that account"
  exit 1
fi

curl -LsS "${AZP_AGENT_PACKAGE_LATEST_URL}" | tar -xz & wait $!
